FROM openjdk:8-jre

MAINTAINER Yohann Paulus <yohann.paulus@heih-vd.ch>

COPY MockMock-1.4.0.one-jar.jar /opt/app/MockMock-1.4.0.one-jar.jar

CMD ["java","-jar","/opt/app/MockMock-1.4.0.one-jar.jar","-p","25"]
